leanprover-community/mathlib-tools

scripts/remote-install-update-mathlib.sh
scripts/setup-dev-scripts.sh
scripts/setup-lean-git-hooks.sh

This PR fixes installation issues when the user name contains spaces, e.g. in Windows or OS X.
The problem is easily fixed by enclosing all the occurrences of the `$HOME` environment variable with double quotes ("). I also changed the messages asking to reload `"$HOME"/.profile` to avoid the same issue when the user types the same command on terminal.

fix(scripts): support spaces in the $HOME env variable

---

scripts/update-mathlib.py

I'm updating an old project with the dependency "https://github.com/leanprover-community/mathlib/". Took me a minute to figure out why `update-mathlib` was failing.
TO CONTRIBUTORS:
Make sure you have:
If this PR is related to a discussion on Zulip, please include a link in the discussion.
For reviewers: [code review check list](https://github.com/leanprover/mathlib/blob/master/docs/code-review.md)

more permissive check for mathlib dependencies

---

README.md
default.nix

This makes it possible to easily install `mathlib-tools` on NixOS.  I've also expanded the readme file a bit.

feat(default.nix): add build file for NixOS

---

setup.py

2.1.11 is the oldest version containing https://github.com/gitpython-developers/GitPython/commit/7f08b7730438bde34ae55bc3793fa524047bb804, and coincidentally the version available in Nixpkgs stable.

Don't bump GitPython version all that much

---

mathlibtools/leanproject.py
mathlibtools/lib.py
mathlibtools/post-commit

When running `leanproject` in CI (and arguably in general), we want it to exit with a non-zero code if the command fails. Here, I make calls to `subprocess.run` raise an exception if the tool fails where that makes sense, so that the exception handler is called and `leanproject` overall exits with an error. Otherwise, builds that clearly failed ([e.g. here](https://github.com/b-mehta/topos/runs/556155330)) still get a green tick.

Raise exceptions on leanpkg and git errors

---

mathlibtools/leanproject.py
mathlibtools/lib.py

Add a new `-b` option to `leanproject get` that creates a new branch instead of failing when the specified branch does not exist.
Fixes #40.

Let `leanproject get -b` create a new branch

---

mathlibtools/lib.py

I haven't tested this; I'm not exactly sure how to do that without messing up my normal mathlibtools install. This is the only method where .gz is mentioned, and the untar command is the same, so I think it's the only place that needs to be modified. But I'm not confident.
TO CONTRIBUTORS:
Make sure you have:
If this PR is related to a discussion on Zulip, please include a link in the discussion.
For reviewers: [code review check list](https://github.com/leanprover/mathlib/blob/master/docs/code-review.md)

 check first for xz archives (closes #48)

---

scripts/install_debian.sh

This is a companion to leanprover-community/leanprover-community.github.io#77, synchronizing the detailed instructions with the automatic script.

Use pipx for installation of mathlibtools

---

mathlibtools/lib.py

 Return correct download path for olean caches fetched from github. 

---

scripts/install_macos.sh

This should be an all-in-one installation script for MacOS, similar to the script for Debian-based Linux distros. I ran these commands on a mostly clean MacOS machine during development, then tested it by `brew uninstall` and `pip uninstall`ing the packages, removing the dotfiles and deleting VS Code from the Applications folder before running the scripts. From the results during development, I expect the commands are robust enough to run on a system with some dependencies already installed.

feat(scripts): installation script for MacOS

---

scripts/install_macos.sh

This prevents elan not being added to the path if it decides to modify `.profile` and pipx creates `.bash_profile` afterward. Confirmed to work by @semorrison.

fix(scripts/install_macos.sh): create `.bash_profile` if it doesn't yet exist

---

mathlibtools/leanproject.py

This PR:
1. hides the aliased commands `up` and `update-mathlib`, only showing `upgrade-mathlib` in the help text
2. allows users to use unique prefixes of commands
In particular, this means that now any of `leanproject up`, `leanproject update`, `leanproject upgrade`, `leanproject update-mathlib`, `leanproject upgrade-mathlib`, will all do as expected.
`leanproject b` will run `leanproject build`, but `leanproject d` will give an error message:
```
Usage: leanproject [OPTIONS] COMMAND [ARGS]...
Try 'leanproject -h' for help.
Error: Too many matches: decls, delete-zombies
```

feat(options): hide aliases for upgrade-mathlib, and allow prefixes

---

mathlibtools/leanproject.py
mathlibtools/post-checkout

This PR:
1. in the post-checkout hook, checks if we're in mathlib (by inspecting leanpkg.toml), and does not run `get-mathlib-cache` if so
2. corrects an error message: when looking for a local cache and failing, it used to say "Failed to fetch mathlib oleans", and now says "Failed to fetch cached oleans".

feat(post-checkout): don't run get-mathlib-cache if in mathlib

---

mathlibtools/lib.py

Combined with #80, this hid/hides what went wrong.

Don't eat stderr when running leanproject decls.

---

mathlibtools/decls.lean

Without this, leanproject decls complains there's no
list.split for me.

Add a missing import for leanproject decls.

---

mathlibtools/lib.py

`src_directory` (on my machine) is a relative path, `lean --path` outputs absolute paths, and `relative_to` fails every time for `abs_path.relative_to(rel_path)`.
Tested on windows.
[Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Diagnosing.20cyclic.20imports/near/218610115)

Fix leanproject import-graph to not produce a graph with no edges

---

mathlibtools/lib.py

Currently if a user is working on mathlib and has a dirty repo and runs `leanproject build` the repo is cleaned.
This seems very bad to me (indeed I have once again lost a bunch of work due to mathlib-tools after https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/git.20hooks/near/210958859 and now this 😢).
This pr will change to not git clean a dirty mathlib.
However I would argue that we should in addition **always prompt the user for confirmation before doing anything destructive**, user error is always possible and a command that says "Build the current project." gives no hint that it will reset your git repo.
Example session:
```
+alex:~/tmp 🐌 leanproject get mathlib
Cloning from git@github.com:leanprover-community/mathlib.git
Enter passphrase for key …
```

dont clean a dirty mathlib project

---

mathlibtools/import_graph.py
mathlibtools/lib.py

This moves `ImportGraph`, along with the imports needed to define it, to a new file.
`LeanProject.import_graph` imports this file when called.
This speeds up `leanproject -h` from 3.4s to 1.9s on my machine

Do not import networkx (and transitively numpy) until it is needed

---

scripts/install_macos.sh

See also https://github.com/Homebrew/discussions/discussions/340
---
@rwbarton and I helped some people to install Lean on their computers. We ran into two problems:
* One error `Calling brew cask install is disabled! Use brew install [--cask] instead.`
The script worked after replacing `brew cask install visual-studio-code` by `brew install --cask visual-studio-code`
See also e.g. https://github.com/Homebrew/discussions/discussions/340
* The other error was that `leanpkg` and `elan` were not in the path after installation, but I think that problem has the same cause. We didn't run `source ~/.profile` after correctly installing mathlibtools.
@Vierkantor @PatrickMassot

fix(install_macos.sh): remove deprecated brew cask install

---

.github/workflows/test_install_scripts.yml
scripts/install_macos.sh

With `elan` and `mathlibtools` itself in Homebrew now, we can cut some of this down.

Simplify the Install Script on macOS to use brew

---

mathlibtools/lib.py

Running `leanproject mk_cache` followed by `leanproject get_cache` in a mathlib repo failed, since `get_cache` only looked for an `xz` file. IIRC we deprecated all other formats. It makes sense for `mk_cache` to use the same format as mathlib CI. This will probably cause minor breakage on upgrade (if anyone actually uses this) but nothing too big.

fix(mk_cache): make xz archive instead of bz2

---

default.nix
mathlibtools/lib.py
setup.py

If leanproject is downloading a file (e.g. mathlib oleans) and gets interrupted, we should not keep around the broken archive file. Otherwise, if you re-run the command, leanproject will think the partial download is in fact a complete archive and it will try to extract a broken file.
This PR fixes that issue by creating a temporary file in the `download` function and moving this over the target file when the download has completed successfully.
I have successfully tested the changes on my Linux computer by running `leanproject get-cache` and interrupting the download, then running `leanproject get-cache` again and verifying the oleans are available. Since atomic operations are OS-specific, someone with access to a Windows computer should definitely test this PR as well.
(Is there a way …

feat(leanproject): download to a tempfile

---

mathlibtools/leanproject.py
mathlibtools/lib.py

`leanproject reduce-imports --file foo.bar` will list imports in `foo/bar.lean` that are imported by other imports of `foo.bar` and could therefore be removed, `--sed` will print out a sed script to cut out those lines.

feat(leanproject) add a function to list imports that can be removed due to being imported transitively

---

.github/workflows/pyinstaller-windows.yml
pyinstaller-requirements.txt

Merging #101 broke master, as the dependencies had changed since that PR was created.
This adds back the dependency, and moves the requirements.txt file to a more sensible place.

fix(ci): Add missing dependency for PyInstaller

---

mathlibtools/git_helpers.py
mathlibtools/leanproject.py
mathlibtools/lib.py
tests/test_git_helpers.py

Roughly implements what is described in [this zulip thread](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/get-mathlib-at-commit/near/213010027).
This walks the commit graph, starting from the current commit and going via all parents, until all paths are "blocked" by a commit that has a cache available. The resulting set of caches are unordered with respect to the git graph; none are parents of the other, so all are equally suitable candidates based on the commit graph alone.
For now, we download all suitable caches but then pick one arbitrarily. By printing out all the caches we downloaded, the user can look at their history and make an educated guess at which one will be best for them; for instance by looking at which has a smaller diff with their current commit, …

feat(get-cache): Perform a topological walk to find all viable caches

---

mathlibtools/lib.py

This at least prints out the number of files extracted so far, which clues the user into the fact that it is making progress.
For instance, on my machine this now shows:
```
Applying cache
files extracted: 1651 [00:18, 90.61/s]
```
where the second line is new.
Instrumenting the extraction doesn't appear to impact performance in any meaningful way.
I tried to make it show a proper progress bar, but that requires knowing the contents of the tar file in advance.
It doesn't seem to be safe to iterate the members of a `tarfile.TarFile` from one thread and read them from another, so I didn't bother exploring further.

feat(get-cache): Show a vague indicator of progress when untar-ing the cache

---

mathlibtools/lib.py

This caused problems for list_decls and other tools, as in https://leanprover.zulipchat.com/#narrow/stream/217875-Is-there.20code.20for.20X.3F/topic/Create.20a.20blueprint/near/251398961
Probably users should still not use hyphens in filenames.

wrap filenames containing hyphens in french quotes when making all.lean

---

CHANGELOG.md
mathlibtools/leanproject.py
mathlibtools/lib.py

Apologies for the size of this PR; my impression was that the semantics of some of the commands were mixed up, and it was easier to change them all at once
* `leanproject mk-cache --force` on a dirty tree:
* Creates a cache entry for `HEAD` that represents the dirty state of the working tree (which is not HEAD!)
* `leanproject get-cache`
* on Mathlib:
* Does a full history search
* Unpacks the full archive over the working tree. If this archive comes from azure, it contains only oleans; if it comes from `mk-cache` it contains all the lean source files too.
* on another project:
* Uses only an exact match
* Always overwrites local lean files, meaning that `get-cache --rev old_revision` acts much like `git checkout old_revision -- .`
* `leanproject get-mathlib-cache`
* on mathlib:
* Behaved …

fix: various improvements to get-cache

---

mathlibtools/__init__.py
mathlibtools/_version.py
setup.py
tests/test_python.py

This allows someone using the python part of the API to get the version number.
This also pre-emptively solves any problems that unicode characters in the readme would cause.

feat(mathlibtools): expose mathlibtools.__version__

---

mathlibtools/lib.py

Logger.warn is spelled Logger.warning.

Remove use of deprecated logging methods.

---

mathlibtools/lib.py

Necessary to prevent words merging

Add a space in a log message spread over two lines

---

mathlibtools/import_graph.py
mathlibtools/leanproject.py

It may be sensible to add this as the default, as the transitive imports are nearly always just clutter.

feat: --reduce flag to omit transitive imports

---

mathlibtools/lib.py

The colours scheme in `import-graph` makes more sense if the "PR" status takes precedence of the "ready" colour.

chore(import-graph): don't overwrite 'PR' colour with 'ready' colour

---

mathlibtools/import_graph.py
mathlibtools/leanproject.py

Previously if you used `--exclude-tactics` any imports that were only imported via transitive dependencies through tactics files would be silently dropped.

feat: add transitive edges when removing tactics nodes from the import-graph

---

mathlibtools/import_graph.py
mathlibtools/leanproject.py

See e.g. https://tqft.net/mathlib4/2022-12-09/data.rat.order.pdf for output. Excludes anything that has been ported, and whose children have been ported.
It seems a nice balance of showing context, but discarding old news.

feat: add --exclude-ported flag for import-graph

---

mathlibtools/import_graph.py
mathlibtools/leanproject.py

Explained at [zulip](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/leanproject.20--port-complete).

feat: --port-complete flag to list completely ported files
